//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sebastian Boldt @SebastianBoldt
//  http://sebastianboldt.com
//

import Foundation

protocol ___VARIABLE_MODULENAME___InteractorOutputProtocol {

}

protocol ___VARIABLE_MODULENAME___InteractorInputProtocol {
    func setPresenter(_ presenter: ___VARIABLE_MODULENAME___PresenterProtocol)
}

class ___VARIABLE_MODULENAME___Interactor: ___VARIABLE_MODULENAME___InteractorInputProtocol {
    private weak var presenter: ___VARIABLE_MODULENAME___PresenterProtocol?
    private let dependencies: ___VARIABLE_MODULENAME___InteractorDependenciesProtocol
    
    init(dependencies: ___VARIABLE_MODULENAME___InteractorDependenciesProtocol) {
        self.dependencies = dependencies
    }
    
    func setPresenter(_ presenter: ___VARIABLE_MODULENAME___PresenterProtocol) {
        self.presenter = presenter
    }
}
