//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sebastian Boldt @SebastianBoldt
//  http://sebastianboldt.com
//

import UIKit

protocol ___VARIABLE_MODULENAME___WireframeProtocol {
    static func makeViewController() -> ___VARIABLE_MODULENAME___ViewController
}

struct ___VARIABLE_MODULENAME___Wireframe: ___VARIABLE_MODULENAME___WireframeProtocol {
    static func makeViewController() -> ___VARIABLE_MODULENAME___ViewController {
        
        let view = ___VARIABLE_MODULENAME___ViewController()
        let router = ___VARIABLE_MODULENAME___Router()

        let interactorDependencies = ___VARIABLE_MODULENAME___InteractorDependencies()
        let presenterDependencies = ___VARIABLE_MODULENAME___PresenterDependencies()

        let interactor = ___VARIABLE_MODULENAME___Interactor(dependencies: interactorDependencies)
        let presenter = ___VARIABLE_MODULENAME___Presenter(dependencies: presenterDependencies, view: view, interactor: interactor, router: router)
        interactor.setPresenter(presenter)
        view.setPresenter(presenter)
        
        return view
    }
}
