//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sebastian Boldt @SebastianBoldt
//  and Christian Elies @crelies
//  http://sebastianboldt.com https://www.christianelies.de
//

import Foundation

protocol ___VARIABLE_MODULENAME___InteractorProtocol {

}

final class ___VARIABLE_MODULENAME___Interactor {
    private let dependencies: ___VARIABLE_MODULENAME___InteractorDependenciesProtocol
    
    init(dependencies: ___VARIABLE_MODULENAME___InteractorDependenciesProtocol) {
        self.dependencies = dependencies
    }
}

extension ___VARIABLE_MODULENAME___Interactor: ___VARIABLE_MODULENAME___InteractorProtocol {
	
}
