//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sebastian Boldt @SebastianBoldt
//  and Christian Elies @crelies
//  http://sebastianboldt.com https://www.christianelies.de
//

import UIKit

protocol ___VARIABLE_MODULENAME___ViewProtocol: ___VARIABLE_MODULENAME___Protocol {
    
}

final class ___VARIABLE_MODULENAME___View: UIView {
    private let presenter: ___VARIABLE_MODULENAME___PresenterProtocol

    init(presenter: ___VARIABLE_MODULENAME___PresenterProtocol) {
        self.presenter = presenter
        super.init(frame: .zero)
        setupView()
        presenter.didReceiveEvent(.viewDidInit)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("Use init(presenter:) instead")
    }
}

extension ___VARIABLE_MODULENAME___View: ___VARIABLE_MODULENAME___ViewProtocol {
    
}

extension ___VARIABLE_MODULENAME___View: ___VARIABLE_MODULENAME___Protocol {
  
}

extension ___VARIABLE_MODULENAME___View {
  	private func setupView() {
        setColors()
  	}

  	private func setColors() {
        backgroundColor = .white
  	}
}
