//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sebastian Boldt @SebastianBoldt
//  http://sebastianboldt.com
//

import Foundation

protocol ___VARIABLE_MODULENAME___RouterProtocol {
    
}

final class ___VARIABLE_MODULENAME___Router: ___VARIABLE_MODULENAME___RouterProtocol {
    
}
